# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fc95b9668e87b4057035588383ee1ed0b60a0bfcbfc73922b65822fde269ed6969cbda96b388eedff0ebe3e0065928bac3d2e35ee0ee2a33f243280d045ef58

test:
  secret_key_base: a21c2420c40b9cca2e7dbdd582a38f7549ea44adee099c1504b269b1ccec36203907cb946e5cdcce9ca953b5d32f6c61c0a41c9a4217117074e5a81c615fa15d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
